### ISSUE TITLE
Why another react-form library?

### ISSUE THREAD

**Issue by kentcdodds** [jsdir/react-simple-forms#1]
I ask, because I'm preparing to make another one as well. Is there a reason you decided to not simply go with [react-forms](http://prometheusresearch.github.io/react-forms/)?

**Comment by ericdfields** [comment]
@jsdir I like where you're headed with this. I cannot get either react-forms or your library behaving well in my app though. I tried the example above and got an Invariant Violation error when It tried to hit here:

	var Field = React.createClass({
	  mixins: [Mixin],
	  render: function() {
	    var element = React.Children.only(this.props.children);
	    return this.makeField(element, {handleEvents: this.props.handleEvents});
	  }
	});

`this.props.children` is undefined.

**Comment by jsdir** [comment]
@ericdfields Sorry for not getting to this sooner. `Field` is meant to wrap any component that uses `value/onChange` to transfer values.

https://github.com/jsdir/react-simple-forms/blob/5e1e65b70ce6a805581cb1caf6274075da0a2263/lib/__tests__/Form-test.jsx#L50-L55

I need to correct the docs to agree with the current implementation. Until then, the tests should show the general usage of the library. Also, be sure to use `react-simple-forms@0.5.1`.

**Comment by ericdfields** [comment]
Thank you.
